### ISSUE TITLE
Question on access rights

### ISSUE THREAD

**Issue by phahulin** [poanetwork/poa-explorer-infra#10]
README states that following permissions are required
```
VPCs and associated networking resources (subnets, routing tables, etc.)
Security Groups
EC2
S3
SSM
DynamoDB
Route53
RDS
```
however it looks like there are some more:
```
* aws_iam_role.deployer: Error creating IAM Role t1234-deployer-role: AccessDenied: User: arn:aws:iam::758011127832:user/test-poa-explorer is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::758011127832:role/t1234-deployer-role

* aws_elasticache_subnet_group.redis: Error creating CacheSubnetGroup: AccessDenied: User: arn:aws:iam::758011127832:user/test-poa-explorer is not authorized to perform: elasticache:CreateCacheSubnetGroup
    status code: 403, request id: 29db6b78-4c8f-11e8-91ec-d7b7dc1ccbae
```
So that in total seems to give more than 10 permissions per user, which is not allowed by AWS, I had to give my use full access.

I'm opening this just to clarify if my thoughts are correct or there's another way to provide required permissions.

**Comment by bitwalker** [comment]
For the provision task, we effectively do require an IAM user with full access, as we touch resources on a number of AWS services. It is not necessary to keep that user (or level of access) around after provisioning, but it is needed for the initial provision, and any time you want to run `provision` to update the infra. I will update the README accordingly.
