### ISSUE TITLE
(Feature) backend.tfvars and main.tfvars overriding terraform.tfvars file

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer-infra#21]
If a user provides the `terraform.tfvars` file, `backend.tfvars` and `main.tfvars` should not override variables found in `terraform.tfvars`.

**Comment by bitwalker** [comment]
This should be fixed in master now, I'll leave this open until we feel confident it is addressed

**Comment by acravenho** [comment]
This can be closed. I haven't experienced any recent issues regarding this problem. 👍
