### ISSUE TITLE
bin/infra -v provision hangs, if no .tfvars provided in repo

### ISSUE THREAD

**Issue by Ykisialiou** [poanetwork/poa-explorer-infra#22]
If I clone clear repo, and no .tfvars file provided, the script hangs after prefix generation process.

I expected it to ask for necessary variables. 

I investigated a little and looks like this will hangs forewer, if $EXTRA_VARS empty. 
https://github.com/poanetwork/poa-explorer-infra/blob/master/bin/infra#L165 
because we will have `cat` without arguments in this case. 

I'n not sure about proper fix, but probably $EXTRA_VARS  should be checked, and some another flow provided, if it's empty.

**Comment by bitwalker** [comment]
This should be fixed in master now
