### ISSUE TITLE
bug is mentioned in README, but

### ISSUE THREAD

**Issue by alexakarpov** [poanetwork/poa-explorer-infra#32]
...but the solution proposed doesn't make sense:

> ```
> Error inspecting states in the "s3" backend:
>     NoSuchBucket: The specified bucket does not exist
>     status code: 404, request id: xxxxxxxx, host id: xxxxxxxx
> 
> Prior to changing backends, Terraform inspects the source and destination
> states to determine what kind of migration steps need to be taken, if any.
> Terraform failed to load the states. The data in both the source and the
> destination remain unmodified. Please resolve the above error and try again.
> ```
> 
> This is due to mismatched variables in `terraform.tfvars` and `main.tfvars` files. Update the `terraform.tfvars` file to match the `main.tfvars` file.

what is this `terraform.tfvar` file, then? It doesn't exist anywhere on the box, and specifically in the cloned repo, before of after the provisioning (that fails with this error). That said, I did inspect the base/terraform.tfstate, and found a suspicious line (3rd below):

> "bucket": "akar-poa-state",
> "bucket_domain_name": "akar-poa-state.s3.amazonaws.com",
> "bucket_regional_domain_name": "akar-poa-state.s3.us-east-2.amazonaws.com",

This is indeed the prefix I've provided, and my bucket name. But this region has nothing to do with my account; the bin/infra script never asked me for my region, neither did the instructions specify any region as required. My ~/.aws/config has this region specified:
 
> [default]
> region = ca-central-1
> output = json

and indeed, the provision step reports bucket and ddb tables being successfully created, and I do see them (in my real region).

**Comment by alexakarpov** [comment]
Oh, my apologies. I seem to have skipped a bit in the beginning of the instructions in README, which does instruct to create that very file!

**Comment by acravenho** [comment]
@alexakarpov You can create this file `terraform.tfvars` (doesn't have to be named this) and include any of these variables `main/variables.tf` within that file. This helps to customize the specific chain that explorer will run. 

It is not necessary to create this file as you will be prompted for the required variables at the start of `bin/infra provision`.

**Comment by alexakarpov** [comment]
yes @acravenho I figured out as much (especially the part of skipping the prompts on every retry). I should've read the README more carefull - it mentions that the file needs to be created, after all.
