### ISSUE TITLE
Error when attempting to verify smart contract

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer-infra#37]
I'm currently receiving the following error when attempting to verify a smart contract:

```Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: 14:01:21.242 request_id=gujis2lcqv0ol5bf6gcdk64uq5vohe1u [info] POST /en/addresses/0x8974cd6822ff825ea9e47bef6416cbf73fd328b6/contract_verifications
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: 14:01:21.249 request_id=gujis2lcqv0ol5bf6gcdk64uq5vohe1u [info] Sent 500 in 7ms
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: 14:01:21.251 [error] #PID<0.8411.4> running ExplorerWeb.Endpoint terminated
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: Server: sokg-explorer-sokol-elb-682326660.us-east-1.elb.amazonaws.com:80 (http)
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: Request: POST /en/addresses/0x8974cd6822ff825ea9e47bef6416cbf73fd328b6/contract_verifications
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: ** (exit) an exception was raised:
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: ** (ErlangError) Erlang error: :enoent
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (elixir) lib/system.ex:622: System.cmd("node", ["/opt/app/_build/prod/lib/explorer/priv/compile_solc.js", "contract SimpleStorage {\r\n    uint storedData;\r\n\r\n    function set(uint x) public {\r\n        storedData = x;\r\n    }\r\n\r\n    function get() public constant returns (uint) {\r\n        return storedData;\r\n    }\r\n}", "v0.4.24+commit.e67f0147", "0"], [])
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer) lib/explorer/smart_contract/solidity/code_compiler.ex:64: Explorer.SmartContract.Solidity.CodeCompiler.run/4
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer) lib/explorer/smart_contract/verifier.ex:24: Explorer.SmartContract.Verifier.evaluate_authenticity/2
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer) lib/explorer/smart_contract/publisher.ex:27: Explorer.SmartContract.Publisher.publish/2
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer_web) lib/explorer_web/controllers/address_contract_verification_controller.ex:24: ExplorerWeb.AddressContractVerificationController.create/2
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer_web) lib/explorer_web/controllers/address_contract_verification_controller.ex:1: ExplorerWeb.AddressContractVerificationController.action/2
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer_web) lib/explorer_web/controllers/address_contract_verification_controller.ex:1: ExplorerWeb.AddressContractVerificationController.phoenix_controller_pipeline/2
Jul 05 14:01:21 ip-10-0-0-159.poa.internal explorer[4039]: (explorer_web) lib/explorer_web/endpoint.ex:1: ExplorerWeb.Endpoint.instrument/4```

**Comment by KronicDeth** [comment]
`:enoent` is the Erlang form of ENOENT from Posix, so it means that the `compile_solc.js` isn't installed.  Did you run the steps in the README to install the JS code for `apps/explorer?

**Comment by acravenho** [comment]
Yes, everything was run and it was working locally before the upload to AWS. Does `:enoent` need to be installed during the `infra` build?

**Comment by bitwalker** [comment]
ENOENT (and the error tuple form in Erlang/Elixir `:enoent`) is just an error code which says that a given file descriptor doesn't exist (it would be translated something like "Error: no such file system entry"). For whatever reason, the that file can't be found on the host, so it either isn't being bundled into the source files uploaded to CodeDeploy, or is being removed somehow - I would suspect the former though.

**Comment by igorffs** [comment]
Is there a chance that this is happening due to missing user permissions?

**Comment by acravenho** [comment]
This file `/opt/app/_build/prod/lib/explorer/priv/compile_solc.js` exists so I'm having issues solving this issue still. I'll keep digging.

**Comment by amandasposito** [comment]
>`cmd(command, args, opts \\ [])`
>`command` is expected to be an executable available in PATH unless an absolute path is given.

https://hexdocs.pm/elixir/System.html#cmd/3

The problem is that the `System.cmd` is not finding the `node` command:

```
[ec2-user@ip-10-0-0-245 explorer]$ node --v
-bash: node: command not found
```

```
[ec2-user@ip-10-0-0-245 explorer]$ iex -S mix
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.6.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> System.find_executable("node")
nil
```

There are two ways of fixing this:

1. Install the `node` globally in the machine;
2. Distribute it in priv and keep the executables in the project repository.

I'm thinking about going with the first option to solve this one, but I'm not sure how we will handle this dependency for the next deploys, maybe add some condition to the `bin/deploy` file as well.

WDYT @bitwalker ?

**Comment by bitwalker** [comment]
Is Node being used for something post-build? If that's the case, then yes, installing Node globally is the best approach. The reason why Node is not installed currently, is because it was (previously) only required during builds to generate front-end assets, so by the time the application was installed on the EC2 host, Node was no longer needed. If that's changed, the `init.sh` script will need to install Node along with the other packages it installs.
