### ISSUE TITLE
Could not compile dependency :keccakf1600

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer-infra#43]
While testing #42 I ran into this problem while CodeDeploy was installing dependencies.

```
[stdout]===> Compiling keccakf1600
[stdout]make: Entering directory `/opt/app/deps/keccakf1600/c_src'
[stdout] C      keccakf1600_nif.c
[stdout] LD     keccakf1600.so
[stdout]/opt/app/deps/keccakf1600/c_src/decaf-utils.o: file not recognized: File format not recognized
[stdout]collect2: error: ld returned 1 exit status
[stdout]make: *** [/opt/app/deps/keccakf1600/c_src/../priv/keccakf1600.so] Error 1
[stdout]make: Leaving directory `/opt/app/deps/keccakf1600/c_src'
[stdout]===> Hook for compile failed!
[stdout]
[stderr]** (Mix) Could not compile dependency :keccakf1600, "/home/ec2-user/.mix/rebar3 bare compile --paths "/opt/app/_build/prod/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile keccakf1600", update it with "mix deps.update keccakf1600" or clean it with "mix deps.clean keccakf1600"
```

**Comment by KronicDeth** [comment]
That's super weird: that means the `o` file created by your C compiler can't be read by your linker (`ld`).  Did you you accidentally upload a macOS version of `decaf-utils.o` inside the tarball for CodeDeploy?  It may be that it isn't regenerating it since the `.o` is newer.

**Comment by amandasposito** [comment]
Maybe that's because we are not installing `automake` at the server, only the `libtool` 🤔 

https://github.com/poanetwork/poa-explorer#requirements

**Comment by acravenho** [comment]
@KronicDeth was correct. They were caused by a macOS version of `decaf-utils.o`. Closing this issue.

**Comment by pdxrod** [comment]
I'm having the same problem. I did git clone https://github.com/poanetwork/blockscout just two days ago, and followed the instructions to install it. Mac O/S 10.13.6, Elixir 1.7.1, Homebrew 1.7.3. Although the issue is 'closed', I can't see how to resolve it:  (Mix) Could not compile dependency :keccakf1600.

**Comment by pdxrod** [comment]
Thanks for the reply

I looks like keccakf1600_nif.c contains references to functions which don't exist in the files it's being linked with. For example, enif_alloc_resource isn't in any file other than keccakf1600_nif.c.

$ cat ./deps/keccakf1600/c_src/keccakf1600_nif.c | grep enif_alloc_resource

ssl_verify_fun (compile)
===> Compiling keccakf1600
 LD     keccakf1600.so
Undefined symbols for architecture x86_64:
  "_enif_alloc_resource", referenced from:
      _keccakf1600_sha3_224_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_224_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_256_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_384_nif_1 in keccakf1600_nif.o
      ...
  "_enif_consume_timeslice", referenced from:
      _keccakf1600_sha3_224_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_256_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_384_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_384_update_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_512_nif_4 in keccakf1600_nif.o
      ...
  "_enif_get_resource", referenced from:
      _keccakf1600_sha3_224_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_256_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_384_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_384_update_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_512_nif_4 in keccakf1600_nif.o
      ...
  "_enif_get_tuple", referenced from:
      _keccakf1600_sha3_224_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_224_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_256_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_384_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_384_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_512_update_nif_2 in keccakf1600_nif.o
      ...
  "_enif_get_ulong", referenced from:
      _keccakf1600_shake128_nif_2 in keccakf1600_nif.o
      _keccakf1600_shake128_final_nif_2 in keccakf1600_nif.o
      _keccakf1600_shake256_nif_2 in keccakf1600_nif.o
      _keccakf1600_shake256_final_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_224_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_4 in keccakf1600_nif.o
      _keccakf1600_sha3_256_nif_4 in keccakf1600_nif.o
      ...
  "_enif_inspect_binary", referenced from:
      _keccakf1600_sha3_224_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_224_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_256_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_384_nif_1 in keccakf1600_nif.o
      ...
  "_enif_make_atom", referenced from:
      _keccakf1600_nif_load in keccakf1600_nif.o
  "_enif_make_badarg", referenced from:
      _keccakf1600_sha3_224_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_224_init_nif_0 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_224_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_init_nif_0 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_2 in keccakf1600_nif.o
      ...
  "_enif_make_new_binary", referenced from:
      _keccakf1600_sha3_224_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_224_init_nif_0 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_224_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_init_nif_0 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_2 in keccakf1600_nif.o
      ...
  "_enif_make_resource", referenced from:
      _keccakf1600_sha3_224_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_256_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_384_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_384_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_512_nif_1 in keccakf1600_nif.o
      ...
  "_enif_make_tuple", referenced from:
      _keccakf1600_sha3_224_init_nif_0 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_256_init_nif_0 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_384_init_nif_0 in keccakf1600_nif.o
      _keccakf1600_sha3_384_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_512_init_nif_0 in keccakf1600_nif.o
      ...
  "_enif_make_ulong", referenced from:
      _keccakf1600_sha3_224_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_256_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_384_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_384_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_512_nif_1 in keccakf1600_nif.o
      ...
  "_enif_open_resource_type", referenced from:
      _keccakf1600_nif_load in keccakf1600_nif.o
      _keccakf1600_nif_upgrade in keccakf1600_nif.o
  "_enif_priv_data", referenced from:
      _keccakf1600_sha3_224_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_224_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_256_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_384_nif_1 in keccakf1600_nif.o
      ...
  "_enif_release_resource", referenced from:
      _keccakf1600_sha3_224_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_224_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_256_final_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_384_nif_1 in keccakf1600_nif.o
      ...
  "_enif_schedule_nif", referenced from:
      _keccakf1600_sha3_224_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_224_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_256_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_256_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_384_nif_1 in keccakf1600_nif.o
      _keccakf1600_sha3_384_update_nif_2 in keccakf1600_nif.o
      _keccakf1600_sha3_512_nif_1 in keccakf1600_nif.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/nshop/dev/blockscout/deps/keccakf1600/c_src/../priv/keccakf1600.so] Error 1
===> Hook for compile failed!

**Comment by KronicDeth** [comment]
In `enif_alloc_resource`, `enif` namespace is short for Erlang NIF, where `NIF` is Native Implemented Function.  It's the C-API thath keccak is using to allocate memory in the VM.  Not being able to find it would indicate you're missing some of the development resources for the Erlang VM in your install.

**Comment by pdxrod** [comment]
Thanks. I think this is what I need: https://www.lambdacat.com/how-to-install-elixir-on-mac/. I'll repot back.

**Comment by pdxrod** [comment]
No, kerl and exenv didn't make any difference

**Comment by KronicDeth** [comment]
@pdxrod homebrew should be enough.  I develop BlockScout using homebrew installs.  Here's the list of everything I have installed.  Obviously, only a subset of this is needed, but it is a place to start for what you are missing:

```sh
> brew list
ack             awscli          ccache          curl            fontconfig      gettext         gnu-sed         gradle          jasper          libarchive      libksba         libtool         lzo             openssl         phantomjs       pkg-config      readline        solidity        ufraw           x264            zbar
adns            bash            cmake           dcraw           freetype        gifsicle        gnupg           heroku          jpeg            libassuan       libpng          libunistring    nettle          openssl@1.1     picocom         postgresql      rebar@3         sphinx-doc      vim             xvid            zsh
ant             bcrypt          confuse         elixir          fwup            git             gnutls          heroku-node     jq              libffi          libsodium       libusb          node            p11-kit         pinentry        pth             redis           sqlite          watch           xz
autoconf        boost           convox          erlang          gdb             glib            go              icu4c           kerl            libgcrypt       libtasn1        libyaml         npth            pcre            pinentry-mac    python          ruby            squashfs        wget            yarn
automake        cairo           coreutils       ffmpeg          gdbm            gmp             gpg-agent       imagemagick     lame            libgpg-error    libtiff         little-cms2     oniguruma       perl            pixman          python@2        scala           terraform       wxmac           z3
```

**Comment by smalaichami** [comment]
I faced the same issue in ubuntu and solved it by upgrading NodeJs version to 14+ from NodeJs 10

**Comment by def670** [comment]
smalaichami was that all you had to do?  I have tried with node 14 and node 12 with same issue.   still down to could not compile dependency : keccakf1600 - on ubuntu 16.04 and 18.04....same error definatly points at me not installing something properly
