### ISSUE TITLE
bin/infra provision did not provide a privkey

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer-infra#47]
I've never seen this issue before where the terraform script deployed successfully but when I was attempting to ssh into the EC2 instance a `.privkey` file was not generated during the deployment stage. 

No action should be taken at this time but I would like to keep note that this has happened.

**Comment by bitwalker** [comment]
This can happen if the key pair name you provide already exists in the AWS account (implying that the key pair already exists, and is handy, so it isn't necessarily an error condition). You probably already have the keys, but if you deleted them, then you'd need to create a new set, update the launch configuration to use the new key pair, and then redeploy (in the case of infra you aren't planning to tear down anyway).

The `infra` script could be tweaked to raise an error in this case, or prompt on what to do, but it does not do so currently.

**Comment by acravenho** [comment]
Thanks, Paul. That is exactly what happened. I had previously used this `prefix`. I appreciate the help :)

**Comment by bitwalker** [comment]
No problem :)
