### ISSUE TITLE
Validate db password length

### ISSUE THREAD

**Issue by phahulin** [poanetwork/poa-explorer-infra#9]
db password must be at least 8 chars long
```
* aws_db_instance.default: Error creating DB Instance: InvalidParameterValue: The parameter MasterUserPassword is not a valid password because it is shorter than 8 characters.
```

**Comment by bitwalker** [comment]
Config values which Terraform prompts for are provided after we hand control to Terraform, so we don't have the opportunity to validate them ourselves. This isn't an issue though, as you just run `bin/infra provision` again after fixing the validation issue, and Terraform will pick up where it left off. I do think we should document the requirements here, so I will do that in the prerequisites section.
